### ISSUE TITLE
don't do this 😳️

### ISSUE THREAD

**Issue by qexat** [ZeroIntensity/pointers.py#24]
don't do this
```py
import ctypes
ctypes.string_at(0)
```
i warned u

~~it just causes a segfault dw, you can also do it by typing `ctypes.cast(1, ctypes.py_object)`~~

**Comment by qexat** [comment]
Jokes aside you should put a segfault in examples since it's a feature :sunglasses:

**Comment by ZeroIntensity** [comment]
i think this actually just raises an `OSError` on windows
