### ISSUE TITLE
3.0.0

### ISSUE THREAD

**Issue by ZeroIntensity** [ZeroIntensity/pointers.py#30]
its time this library gets another rewrite.

this should include the following:
- all existing features
- patches for all ffi problems
- fixed ci
- better unit testing

**Comment by ZeroIntensity** [comment]
i forgot :skull:

**Comment by 0Mayank** [comment]
![image](https://github.com/ZeroIntensity/pointers.py/assets/40265635/b17c5b16-be22-4dcc-87a9-87156a9e736c)

**Comment by ZeroIntensity** [comment]
im busy with other stuff ok
