### ISSUE TITLE
Feature Request: malloc

### ISSUE THREAD

**Issue by Gorlph** [ZeroIntensity/pointers.py#5]
Why not?

**Comment by x9prototype** [comment]
Don't forget `free()` as well, don't want those memory leaks

**Comment by ZeroIntensity** [comment]
there isn't really any good way for this to work in python. ill look into it though

**Comment by ZeroIntensity** [comment]
i think i found a way to do this, working on it

**Comment by ZeroIntensity** [comment]
implemented in 1.1.2

**Comment by Gorlph** [comment]
I did ask for it. Thanks for fulfilling my cursed wish.
