### ISSUE TITLE
Tricky question

### ISSUE THREAD

**Issue by bswck** [ZeroIntensity/pointers.py#8]
Will this work on PyPy? ;)

**Comment by ZeroIntensity** [comment]
im not entirely sure, probably not due this library heavily relying on cpython features (such as the id function)

**Comment by bswck** [comment]
Yeah, the `id()` function works differently there. It's good to be aware of, though it's not that important for this concrete library to support it unless it's for something else than just experiments and learning. Cool project, have fun with that!
